import type { AutoHrefManifest, RouteRecord } from "./manifest.ts";

/**
 * Renders the generated declaration file that gives projects autocomplete
 * unions while still accepting arbitrary strings.
 *
 * @example
 * ```ts
 * const code = render_types({
 *   version: 1,
 *   routes_dir: "src/routes",
 *   routes: [],
 * });
 * ```
 *
 * @since 0.1.0
 * @param manifest - Manifest produced by {@link scan_routes}.
 * @returns TypeScript declaration content.
 */
export function render_types(manifest: AutoHrefManifest): string {
  const concrete_entries = collect_entries(manifest);
  const page_pathnames = collect_pathnames(manifest, "page");
  const endpoint_pathnames = collect_pathnames(manifest, "endpoint");
  const concrete_entry_union = render_union(concrete_entries);
  const page_pathname_union = render_union(page_pathnames);
  const endpoint_pathname_union = render_union(endpoint_pathnames);

  return [
    "/* This file is generated by svelte-auto-href. Do not edit it manually. */",
    "",
    'import type { PathnameWithSearchOrHash } from "$app/types";',
    "",
    "type LooseString = string & {};",
    "type WithSearchOrHash<T extends string> = T | `${T}?${string}` | `${T}#${string}`;",
    `type ConcreteEntryPathname = ${concrete_entry_union};`,
    "type ConcreteEntryHref = WithSearchOrHash<ConcreteEntryPathname>;",
    `type GeneratedPagePathname = ${page_pathname_union};`,
    `type GeneratedEndpointPathname = ${endpoint_pathname_union};`,
    "type GeneratedPageHref = WithSearchOrHash<GeneratedPagePathname>;",
    "type GeneratedEndpointHref = WithSearchOrHash<GeneratedEndpointPathname>;",
    "type GeneratedStrictAppHref = PathnameWithSearchOrHash | ConcreteEntryHref;",
    "type GeneratedAutoHref = GeneratedStrictAppHref | LooseString;",
    "",
    "interface AutoHrefGotoOptions {",
    "  replaceState?: boolean | undefined;",
    "  noScroll?: boolean | undefined;",
    "  keepFocus?: boolean | undefined;",
    "  invalidateAll?: boolean | undefined;",
    "  invalidate?: (GeneratedAutoHref | URL | ((url: URL) => boolean))[] | undefined;",
    "  state?: App.PageState | undefined;",
    "}",
    "",
    'declare module "svelte-auto-href/generated" {',
    "  export type AutoHref = GeneratedAutoHref;",
    "  export type StrictAppHref = GeneratedStrictAppHref;",
    "  export type PageHref = GeneratedPageHref | LooseString;",
    "  export type EndpointHref = GeneratedEndpointHref | LooseString;",
    "  export type ConcreteEntryHref = WithSearchOrHash<ConcreteEntryPathname>;",
    "}",
    "",
    'declare module "svelte-auto-href" {',
    "  export function literal_href<T extends GeneratedAutoHref>(value: T): T;",
    "  export function strict_href<T extends GeneratedStrictAppHref>(value: T): T;",
    "}",
    "",
    'declare module "$app/navigation" {',
    "  export function goto(url: GeneratedAutoHref | URL, opts?: AutoHrefGotoOptions): Promise<void>;",
    "  export function invalidate(resource: GeneratedAutoHref | URL | ((url: URL) => boolean)): Promise<void>;",
    '  export function preloadData(href: GeneratedAutoHref): Promise<{ type: "loaded"; status: number; data: Record<string, any> } | { type: "redirect"; location: string }>;',
    "  export function preloadCode(pathname: GeneratedAutoHref): Promise<void>;",
    "  export function pushState(url: GeneratedAutoHref | URL, state: App.PageState): void;",
    "  export function replaceState(url: GeneratedAutoHref | URL, state: App.PageState): void;",
    "}",
    "",
    'declare module "@sveltejs/kit" {',
    "  export function redirect(status: 300 | 301 | 302 | 303 | 304 | 305 | 306 | 307 | 308 | ({} & number), location: GeneratedAutoHref | URL): never;",
    "}",
    "",
    "export {};",
    "",
  ].join("\n");
}

function collect_entries(manifest: AutoHrefManifest): string[] {
  return [...new Set(manifest.routes.flatMap((route) => route.entries))].sort();
}

function collect_pathnames(
  manifest: AutoHrefManifest,
  route_kind: "page" | "endpoint",
): string[] {
  const pathnames = new Set<string>();

  for (const route of manifest.routes) {
    if (!route_matches_kind(route, route_kind)) {
      continue;
    }

    for (const template of route.templates) {
      pathnames.add(template);
    }

    for (const entry of route.entries) {
      pathnames.add(entry);
    }
  }

  return [...pathnames].sort();
}

function route_matches_kind(
  route: RouteRecord,
  route_kind: "page" | "endpoint",
): boolean {
  if (route.route_kind === "page-and-endpoint") {
    return true;
  }

  return route.route_kind === route_kind;
}

function render_union(values: readonly string[]): string {
  if (values.length === 0) {
    return "never";
  }

  return values.map(render_type_literal).join(" | ");
}

function render_type_literal(value: string): string {
  if (value.includes("${string}")) {
    return `\`${value}\``;
  }

  return JSON.stringify(value);
}
